# Generated by Django 4.1.3 on 2022-12-12 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_usuario_senha'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
