# Generated by Django 4.1.3 on 2022-11-06 15:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despesas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=256)),
                ('data', models.CharField(max_length=256)),
                ('descricao', models.CharField(max_length=256)),
                ('tipo_divisao', models.CharField(choices=[('IGUAL', 'Dividido igualmente'), ('DESIGUAL', 'Dividido desigualmente'), ('PERCENTUALMENTE', 'Dividido percentualmente')], default='IGUAL', max_length=25)),
                ('valor_total', models.FloatField()),
                ('valor_atribuido', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
            ],
        ),
    ]
