# Generated by Django 4.1.3 on 2022-11-06 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
        ('despesas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesas',
            name='usuario_criador',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='criador', to='usuario.usuario'),
        ),
        migrations.AddField(
            model_name='despesas',
            name='usuarios_relacionados',
            field=models.ManyToManyField(related_name='relacionados', to='usuario.usuario'),
        ),
        migrations.AlterField(
            model_name='despesas',
            name='tipo_divisao',
            field=models.CharField(choices=[('IGUAL', 'Dividido igualmente'), ('DESIGUAL', 'Dividido desigualmente'), ('PERCENTUAL', 'Dividido percentualmente')], default='IGUAL', max_length=25),
        ),
    ]
