# Generated by Django 4.1.3 on 2022-12-08 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0003_despesas_status_saldodespesas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='despesas',
            name='usuario_criador',
        ),
    ]
