# Generated by Django 4.1.3 on 2022-12-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('despesas', '0005_alter_despesas_usuarios_relacionados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesas',
            name='valor_atribuido',
            field=models.CharField(max_length=256),
        ),
    ]
